#!/bin/zsh

current_branch=`git rev-parse --abbrev-ref HEAD`

if [ "$current_branch" = "main" ]; then
    echo "Running pytest."
    cd assignment4
    pytest
    if [ $? -eq 0 ]; then
        echo "All tests have passed".
        cd ..
        exit 0
    else
        echo "Some test has failed."
        cd ..
        exit 1
    fi
fi


